import React from "react";
import { Box, Stack, Typography } from "@mui/material";
import { blue } from "@mui/material/colors";

import RetirementForm from "./RetirementForm";

const RetirementInfo = (props) => {
    return (
        <Stack
            id="retirement-info"
            className="content-container"
            bgcolor={blue[50]}
            direction={{ xs: "column", lg: "row" }}
            spacing={4}
            py="5vh"
        >
            <Box width={{ xs: 1, lg: 0.6 }}>
                <Typography variant="h1" gutterBottom>
                    Retirement
                </Typography>

                <Typography variant="p" display="block" gutterBottom>
                    Millions of Americans rely on Social Security for income
                    during retirement. To ensure finanical well-being, most
                    American adults also invest in retirement assets such as
                    401(k) plans, pensions, or IRAs.
                </Typography>

                <Typography variant="p">
                    However, no matter the type of retirement investment,
                    starting early is imperative to take advantage of immense
                    wealth generated by time and compound interest.
                </Typography>
            </Box>
            <RetirementForm {...props} />
        </Stack>
    );
};

export default RetirementInfo;
