import React from "react";
import { Paper, Typography } from "@mui/material";

const RetirementForm = (props) => {
    const { retirement, setRetirement } = props;

    return (
        <Paper id="retirement-info" elevation={0} sx={{ p: 4 }}>
            <Typography variant="h1" textAlign="center" gutterBottom>
                Retirement
            </Typography>

            <Typography variant="p">
                Millions of Americans rely on Social Security to produce income
                during retirement. To ensure finanical well-being, most American
                adults also invest in retirement assets such as 401(k) plans
                offerred by their employer, pensions, or IRAs. However, no
                matter the type of retirement investment, starting early is
                imperative to take advantage of immense wealth generated by time
                and compounded interest.
            </Typography>
        </Paper>
    );
};

export default RetirementForm;
